project:
  type: website
  output-dir: docs

website:
  title: "Boating and Angling Interview Trial (BAIT)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Project Description.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



